{
 "title": "Windows-File Analysis Report",
 "tags": [ "windows" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "File Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of disk files",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan;",
     "rawQueryText": " select count(*) from tablescan;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "The total number of files per drive letter",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "queryText": "select drive_letter ,count(*) as file_num ,SUM(file_size)/1024/1024/1024 as `filesize(G)` from tablescan group by drive_letter",
     "rawQueryText": "select drive_letter ,count(*) as file_num ,SUM(file_size)/1024/1024/1024 as `filesize(G)` from tablescan group by drive_letter",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "The latest file under each drive letter",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "select a.drive_letter  ,a.file_name  ,a.file_modified_time  from tablescan a,(select drive_letter,max(file_modified_time) as lasttime from tablescan group by drive_letter) b \r\nwhere a.drive_letter=b.drive_letter and a.file_modified_time=b.lasttime order by a.drive_letter",
     "rawQueryText": "select a.drive_letter  ,a.file_name  ,a.file_modified_time  from tablescan a,(select drive_letter,max(file_modified_time) as lasttime from tablescan group by drive_letter) b \r\nwhere a.drive_letter=b.drive_letter and a.file_modified_time=b.lasttime order by a.drive_letter",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Count file size for the first level directory below each drive letter",
   "type": "barchart",
   "gridPos": { "h": 30, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "queryText": "select  case when first_level_directory='' then drive_letter else first_level_directory end as first_level_directory_path,\r\nsum(file_size)/1024/1024 as `filesize_M` \r\nfrom tablescan group by  first_level_directory order by sum(file_size) desc",
     "rawQueryText": "select  case when first_level_directory='' then drive_letter else first_level_directory end as first_level_directory_path,\r\nsum(file_size)/1024/1024 as `filesize_M` \r\nfrom tablescan group by  first_level_directory order by sum(file_size) desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "select drive_letter,sum(file_size)/1024/1024/1024 as `Disk Used Size(G)`,count(*) as `Total number of disk files` from tablescan group by drive_letter",
     "rawQueryText": "select drive_letter,sum(file_size)/1024/1024/1024 as `Disk Used Size(G)`,count(*) as `Total number of disk files` from tablescan group by drive_letter",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "The total number of each file type",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "queryText": " select file_extension as 文件扩展名,count(*) as 统计个数 from tablescan group by file_extension order by file_extension",
     "rawQueryText": " select file_extension as 文件扩展名,count(*) as 统计个数 from tablescan group by file_extension order by file_extension",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Disk symbol distribution pie chart",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select  drive_letter,count(*) as numcount  from tablescan group by drive_letter",
     "rawQueryText": " select  drive_letter,count(*) as numcount  from tablescan group by drive_letter",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Image Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "disk files-jpg",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='jpg';",
     "rawQueryText": " select count(*) from tablescan where file_extension='jpg';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-bmp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='bmp';",
     "rawQueryText": " select count(*) from tablescan where file_extension='bmp';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-jpeg",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='jpeg';",
     "rawQueryText": " select count(*) from tablescan where file_extension='jpeg';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-png",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='png';",
     "rawQueryText": " select count(*) from tablescan where file_extension='png';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-tif",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='tif';",
     "rawQueryText": " select count(*) from tablescan where file_extension='tif';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-gif",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='gif';",
     "rawQueryText": " select count(*) from tablescan where file_extension='gif';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-psd",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='psd';",
     "rawQueryText": " select count(*) from tablescan where file_extension='psd';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-raw",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='raw';",
     "rawQueryText": " select count(*) from tablescan where file_extension='raw';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Document Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "disk files-doc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='doc';",
     "rawQueryText": " select count(*) from tablescan where file_extension='doc';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-docx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='docx';",
     "rawQueryText": " select count(*) from tablescan where file_extension='docx';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-xls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='xls';",
     "rawQueryText": " select count(*) from tablescan where file_extension='xls';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-xlsx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='xlsx';",
     "rawQueryText": " select count(*) from tablescan where file_extension='xlsx';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-ppt",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='ppt';",
     "rawQueryText": " select count(*) from tablescan where file_extension='ppt';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-pptx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='pptx';",
     "rawQueryText": " select count(*) from tablescan where file_extension='pptx';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-vsd",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='vsd';",
     "rawQueryText": " select count(*) from tablescan where file_extension='vsd';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-vsdx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='vsdx';",
     "rawQueryText": " select count(*) from tablescan where file_extension='vsdx';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-json",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='json';",
     "rawQueryText": " select count(*) from tablescan where file_extension='json';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-txt",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='txt';",
     "rawQueryText": " select count(*) from tablescan where file_extension='txt';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-conf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='conf';",
     "rawQueryText": " select count(*) from tablescan where file_extension='conf';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-csv",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='csv';",
     "rawQueryText": " select count(*) from tablescan where file_extension='csv';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-log",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='log';",
     "rawQueryText": " select count(*) from tablescan where file_extension='log';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-pdf",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='pdf';",
     "rawQueryText": " select count(*) from tablescan where file_extension='pdf';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-bat",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='bat';",
     "rawQueryText": " select count(*) from tablescan where file_extension='bat';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-html",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='html';",
     "rawQueryText": " select count(*) from tablescan where file_extension='html';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-eml",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='eml';",
     "rawQueryText": " select count(*) from tablescan where file_extension='eml';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-ini",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='ini';",
     "rawQueryText": " select count(*) from tablescan where file_extension='ini';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Audio Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "disk files-wav",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='wav';",
     "rawQueryText": " select count(*) from tablescan where file_extension='wav';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-flac",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='flac';",
     "rawQueryText": " select count(*) from tablescan where file_extension='flac';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-ape",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='ape';",
     "rawQueryText": " select count(*) from tablescan where file_extension='ape';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-aiff",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='aiff';",
     "rawQueryText": " select count(*) from tablescan where file_extension='aiff';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-mp3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='mp3';",
     "rawQueryText": " select count(*) from tablescan where file_extension='mp3';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-wma",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='wma';",
     "rawQueryText": " select count(*) from tablescan where file_extension='wma';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-aac",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='aac';",
     "rawQueryText": " select count(*) from tablescan where file_extension='aac';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Video Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "disk files-mpeg",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='mpeg';",
     "rawQueryText": " select count(*) from tablescan where file_extension='mpeg';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-3gp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='3gp';",
     "rawQueryText": " select count(*) from tablescan where file_extension='3gp';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-rm",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='rm';",
     "rawQueryText": " select count(*) from tablescan where file_extension='rm';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-rmvb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='rmvb';",
     "rawQueryText": " select count(*) from tablescan where file_extension='rmvb';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-wmv",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='wmv';",
     "rawQueryText": " select count(*) from tablescan where file_extension='wmv';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-flv",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='flv';",
     "rawQueryText": " select count(*) from tablescan where file_extension='flv';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-mkv",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='mkv';",
     "rawQueryText": " select count(*) from tablescan where file_extension='mkv';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-mp4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='mp4';",
     "rawQueryText": " select count(*) from tablescan where file_extension='mp4';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-mov",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='mov';",
     "rawQueryText": " select count(*) from tablescan where file_extension='mov';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-m4v",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='m4v';",
     "rawQueryText": " select count(*) from tablescan where file_extension='m4v';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Compress Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true
  },
  {
   "title": "disk files-zip",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) as num from tablescan where file_extension='zip';",
     "rawQueryText": " select count(*) as num from tablescan where file_extension='zip';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-rar",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='rar';",
     "rawQueryText": " select count(*) from tablescan where file_extension='rar';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-gz",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='gz';",
     "rawQueryText": " select count(*) from tablescan where file_extension='gz';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-7z",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='7z';",
     "rawQueryText": " select count(*) from tablescan where file_extension='7z';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Other File", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "disk files-msi",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='msi';",
     "rawQueryText": " select count(*) from tablescan where file_extension='msi';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-exe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='exe';",
     "rawQueryText": " select count(*) from tablescan where file_extension='exe';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-tmp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='tmp';",
     "rawQueryText": " select count(*) from tablescan where file_extension='tmp';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "disk files-dll",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": " select count(*) from tablescan where file_extension='dll';",
     "rawQueryText": " select count(*) from tablescan where file_extension='dll';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}